NapNeko/NapCatQQ

- src/onebot11/config.ts
发生错误直接被 catch 掉了，没有提示，[使用docker启动后，请求被重置](https://github.com/NapNeko/NapCat-Docker/issues/8)
> feat(onebot11):  Improve error handling in JSON parsing

- src/onebot11/constructor.ts
- src/onebot11/event/notice/OB11FriendAddNoticeEvent.ts
- src/onebot11/main.ts
https://github.com/botuniverse/onebot-11/blob/d4456ee706f9ada9c2dfde56a2bcfc69752600e4/event/notice.md?plain=1#L98-L109
> feat: add FriendAddNoticeEvent

- src/onebot11/action/group/GetGroupMemberList.ts
- src/onebot11/action/group/LRUCache.ts
- src/onebot11/action/group/LastSendAndJoinRemberLRU.ts
- src/onebot11/config.ts
- src/onebot11/main.ts
解决了如果机器人不是管理员的情况下无法获取到发言时间的问题（加群时间还没做）
> 对 get_group_member_list 增强

- package.json
- src/common/utils/AsyncQueue.ts
- src/common/utils/QQBasicInfo.ts
- src/common/utils/audio.ts
- src/common/utils/cpmodule.ts
- src/common/utils/db.ts
- src/common/utils/file.ts
- src/common/utils/log.ts
- src/common/utils/video.ts
- src/index.ts
- src/onebot11/action/system/CleanCache.ts
- src/onebot11/log.ts
- src/onebot11/main.ts
- src/webui/index.ts
- src/webui/src/helper/config.ts
给log一点颜色看看）
把散落的console.log/console.error换成log4js的方法
没有很理解不能多登的客户端为什么要显示登陆账号信息）
> fix: 整理日志、添加颜色、使用统一的日志函数以提高日志可读性

- src/onebot11/server/ws/ReverseWebsocket.ts
添加 "User-Agent": "OneBot/11" 来让OtterBot项目能够识别ws连接
> feat: ws反代请求添加UA: OneBot/11

- src/common/utils/file.ts
尝试获取更详细的错误信息，避免拿到 `${url}下载失败,TypeError: fetch failed`
> fix: error catch

- package.json
- src/common/utils/audio.ts
> perf: audio

- src/onebot11/constructor.ts
- src/onebot11/event/notice/OB11PokeEvent.ts
- src/onebot11/log.ts
> 群戳一戳增加原始信息

- src/common/utils/ConfigBase.ts
- src/core/src/utils/config.ts
- src/onebot11/config.ts
用户登录新账号的时候，可以直接修改默认配置，以变更新账号的默认配置
> feat[config]support use default-template

- src/onebot11/constructor.ts
- src/onebot11/event/notice/OB11FriendAddNoticeEvent.ts
> feat: support FriendAddNoticeEvent

- src/onebot11/constructor.ts
- src/onebot11/cqcode.ts
- src/onebot11/types/message.ts
ref https://github.com/LLOneBot/LLOneBot/pull/315
> feat: at segment add name

- src/framework/napcat.cjs
> fix: 框架启动概率性失败

- src/onebot/action/user/GetCookies.ts
> fix: GetCookie容错

- src/shell/napcat.ts
> fix: 二维码登录

- LICENSE
修改License,从法律层面禁止在公共社交媒体宣传，在一定程度上增加项目的存在时间
> 修改许可证以禁止宣传

- src/onebot/index.ts
> Fix bug: active HTTP adapter

- src/core/apis/group.ts
> fix: 群成员列表获取

- src/onebot/api/group.ts
> fix: 踢官方机器人报错

- src/onebot/api/msg.ts
> fix: friend_add

- src/onebot/api/msg.ts
- src/onebot/index.ts
> Revert "fix: 好友添加成功事件"

- launcher/qqnt.json
> chore: 增加下载链接HASH
